"""empty message

Revision ID: fcc5e5c0a3bf
Revises: 9efe4ed45736
Create Date: 2023-05-10 22:14:05.693301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc5e5c0a3bf'
down_revision = '9efe4ed45736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###
